version: '3.8'
name: javapro1-hw4-db

services:
  db:
    image: postgres:17-alpine
    container_name: javapro1-hw4-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: hw4
    ports:
      - '5435:5432'
    volumes:
      - javapro1-hw4-db:/var/lib/postgresql/data

volumes:
  javapro1-hw4-db:
