server:
  port: ${SERVER_PORT}
spring:
  application:
    name: hw4
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
  liquibase:
    enabled: true
    change-log: db.changelog/changelog.yml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: validate

springdoc:
  swagger-ui:
    enabled: true
